[[constraint]]
    name = "github.com/richp10/dat"
    version="v2.0.2"
[[constraint]]
    name = "github.com/smartystreets/goconvey"
    version = "1.6.3"
[[constraint]]
    name = "github.com/aws/aws-sdk-go"
[[constraint]]
    name = "github.com/o1egl/govatar"
    version = "0.2.0"
[[constraint]]
     name = "github.com/jmoiron/jsonq"
[[constraint]]
     name = "github.com/anthonynsimon/bild"
     branch = "master"
[[constraint]]
     name = "github.com/muesli/smartcrop"
[[constraint]]
     name = "github.com/h2non/filetype"
[[constraint]]
     name = "github.com/matcornic/hermes"
[[constraint]]
    name = "github.com/go-mail/mail"
    version= "2.2.0"
[[constraint]]
     name = "github.com/wcharczuk/go-chart"
[[constraint]]
     name = "github.com/spf13/viper"
[[constraint]]
     name = "github.com/davecgh/go-spew"
[[constraint]]
     name = "github.com/armon/consul-api"
[[constraint]]
     name = "github.com/satori/go.uuid"
     revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
[[constraint]]
     name = "github.com/lib/pq"
[[constraint]]
    name = "github.com/sirupsen/logrus"
[[constraint]]
    name = "github.com/fsnotify/fsnotify"
[[constraint]]
    name = "github.com/gorilla/sessions"
[[constraint]]
    name = "github.com/gorilla/csrf"